#include "FreeRTOS.h"
#include "task.h"
#include "i2c.h"
#include "ssd1306.h"
#include "uart.h"
#include "adc.h"
#include "bms.h"
#include "cli.h"
#include "can.h"
#include <stdio.h>

#define SCB_CPACR  (*(volatile uint32_t*)0xE000ED88UL)
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
* @brief FreeRTOS malloc failed hook — halts on heap exhaustion.
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationMallocFailedHook(void) {
    taskDISABLE_INTERRUPTS();
    while(1);
}

/**
* @brief FreeRTOS stack overflow hook — halts on task stack overflow.
*
* @param xTask Task handle of the offending task
* @param pcTaskName Name string of the offending task
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationStackOverflowHook(TaskHandle_t xTask, char* pcTaskName) {
    (void)xTask;
    (void)pcTaskName;
    taskDISABLE_INTERRUPTS();
    while(1);
}



int main(void)
{
	SCB_CPACR |= ((3UL << 10*2) | (3UL << 11*2));

	UART_init();
	UART_send_str("UART ready\r\n");
    ADC_init();
    UART_send_str("ADC ready\r\n");
    BMS_init();

    CAN_Filter_t test_cfg = {
        .mask_mode.id[0] = 0x000,
        .mask_mode.mask[0] = 0x000,
        .bank = 0,
        .fifo = 0,
        .mode = CAN_FILTER_MASK,
        .scale = CAN_FILTER_32BIT
    };

    CAN_init();
    CAN_filter_init(&test_cfg);

    if(!(CAN1->MSR & (1U))) {
        UART_send_str("CAN in NORMAL mode\r\n");
    }else {
        UART_send_str("ERROR\r\n");
    }

    if(!(CAN1->MSR & (1U << 1))) {
        UART_send_str("CAN not sleeping\r\n");
    }

	while(1) {
		if(get_UART_IRQ_FLAG()) {
            CLI_command_parser(get_UART_IRQ_CMD());
        }
    }

    
    /* BATTERY CIRCUIT TESTING
    ADC_init();
    UART_send_str("ADC ready\r\n");
    uint16_t raw1 = ADC_single_conversion(CELL1_CHANNEL);
   
    UART_send_str("CELL 1: ");
    UART_print_int(raw1);
    UART_send_str("\r\n");

    uint16_t raw2 = ADC_single_conversion(CELL2_CHANNEL);

    UART_send_str("CELL 2: ");
    UART_print_int(raw2);
    UART_send_str("\r\n");
    */



}

