#include "FreeRTOS.h"
#include "task.h"
#include "i2c.h"
#include "ssd1306.h"
#include "uart.h"

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
* @brief FreeRTOS malloc failed hook — halts on heap exhaustion.
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationMallocFailedHook(void) {
    taskDISABLE_INTERRUPTS();
    while(1);
}

/**
* @brief FreeRTOS stack overflow hook — halts on task stack overflow.
*
* @param xTask Task handle of the offending task
* @param pcTaskName Name string of the offending task
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationStackOverflowHook(TaskHandle_t xTask, char* pcTaskName) {
    (void)xTask;
    (void)pcTaskName;
    taskDISABLE_INTERRUPTS();
    while(1);
}



int main(void)
{
	UART_init();
	UART_send_str("UART ready\n");

	I2C_init();
    UART_send_str("I2C ready\n");

    SSD1306_init();
    UART_send_str("OLED ready\n");
    
    SSD1306_fill(0x00);
    SSD1306_set_cursor(0, 0);
    SSD1306_print_str("C1:3.7V                       C2:3.6V");

    SSD1306_set_cursor(0, 2);
    SSD1306_print_str("C3:3.8V                       C4:3.7V");

    SSD1306_set_cursor(0, 4);
    SSD1306_print_str("SOC:85%                      T:25C");

    SSD1306_set_cursor(0, 6);
    SSD1306_print_str("STATUS: OK");
    UART_send_str("Done\n");

    while(1);
	
}
