#include "FreeRTOS.h"
#include "task.h"
#include "i2c.h"
#include "ssd1306.h"
#include "uart.h"
#include "adc.h"
#include "bms.h"
#include "cli.h"
#include <stdio.h>

#define SCB_CPACR  (*(volatile uint32_t*)0xE000ED88UL)
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
* @brief FreeRTOS malloc failed hook — halts on heap exhaustion.
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationMallocFailedHook(void) {
    taskDISABLE_INTERRUPTS();
    while(1);
}

/**
* @brief FreeRTOS stack overflow hook — halts on task stack overflow.
*
* @param xTask Task handle of the offending task
* @param pcTaskName Name string of the offending task
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationStackOverflowHook(TaskHandle_t xTask, char* pcTaskName) {
    (void)xTask;
    (void)pcTaskName;
    taskDISABLE_INTERRUPTS();
    while(1);
}



int main(void)
{
	SCB_CPACR |= ((3UL << 10*2) | (3UL << 11*2));

	UART_init();
	UART_send_str("UART ready\r\n");
    ADC_init();
    UART_send_str("ADC ready\r\n");

    // OLED TESTING
	I2C_init();
    UART_send_str("I2C ready\n");

    SSD1306_init();
    UART_send_str("OLED ready\n");
    
    SSD1306_fill(0x00);


	while(1) {
		if(get_UART_IRQ_FLAG()) {
            CLI_command_parser(get_UART_IRQ_CMD());
        }

        
        SSD1306_set_cursor(0, 0);

        float voltages[4] = {0};
        uint16_t raw[4] = {0};
        uint32_t sum = 0;
        
        /*OVERSAMPLING*/
        for(uint8_t i = 0; i < 16; i++)
            sum += ADC_single_conversion(CELL1_CHANNEL);
        raw[0] = (uint16_t)(sum / 16);
       
        sum = 0;
        for(uint8_t i = 0; i < 16; i++)
            sum += ADC_single_conversion(CELL2_CHANNEL);
        raw[1] = (uint16_t)(sum / 16);
        
        sum = 0;
        for(uint8_t i = 0; i < 16; i++)
            sum += ADC_single_conversion(CELL3_CHANNEL);
        raw[2] = (uint16_t)(sum / 16);
        
        sum = 0;
        for(uint8_t i = 0; i < 16; i++)
            sum += ADC_single_conversion(CELL4_CHANNEL);
        raw[3] = (uint16_t)(sum / 16);
        
        BMS_calculate_cell_voltage(raw, voltages, 4);

        char line_1[64];
        sprintf(line_1, "C1:%.1fV", voltages[0]);
        SSD1306_print_str(line_1);

        SSD1306_set_cursor(72,0);
        sprintf(line_1,"C2:%.1fV", voltages[1]);
        SSD1306_print_str(line_1);

        char line_2[64];
        SSD1306_set_cursor(0, 2);
        sprintf(line_2, "C3:%.1fV", voltages[2]);
        SSD1306_print_str(line_2);

        SSD1306_set_cursor(72,2);
        sprintf(line_2, "C4:%.1fV", voltages[3]);
        SSD1306_print_str(line_2);

        float avg = BMS_avg_voltage(voltages, 4);
        float soc = BMS_calculate_charge(avg);

        char line_3[64];
        SSD1306_set_cursor(0, 4);
        sprintf(line_3, "SOC: %.1f", soc);
        SSD1306_print_str(line_3);
        SSD1306_print_str("%");

        BMS_Status_t status = BMS_check_fault(voltages, 4);
        SSD1306_set_cursor(0, 6);
        if(status == OK) {
            SSD1306_print_str("STATUS: OK");
        } else {
            SSD1306_print_str("STATUS: FAULT");
        }

        for(uint32_t i = 0; i < 80000; i++) {
            __asm("NOP");
        }
	}

    
    /* BATTERY CIRCUIT TESTING
    ADC_init();
    UART_send_str("ADC ready\r\n");
    uint16_t raw1 = ADC_single_conversion(CELL1_CHANNEL);
   
    UART_send_str("CELL 1: ");
    UART_print_int(raw1);
    UART_send_str("\r\n");

    uint16_t raw2 = ADC_single_conversion(CELL2_CHANNEL);

    UART_send_str("CELL 2: ");
    UART_print_int(raw2);
    UART_send_str("\r\n");
    */



}

