#include "FreeRTOS.h"
#include "task.h"

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
* @brief FreeRTOS malloc failed hook — halts on heap exhaustion.
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationMallocFailedHook(void) {
    taskDISABLE_INTERRUPTS();
    while(1);
}

/**
* @brief FreeRTOS stack overflow hook — halts on task stack overflow.
*
* @param xTask Task handle of the offending task
* @param pcTaskName Name string of the offending task
*
* @note Do not call directly — invoked automatically by FreeRTOS kernel.
*/
void vApplicationStackOverflowHook(TaskHandle_t xTask, char* pcTaskName) {
    (void)xTask;
    (void)pcTaskName;
    taskDISABLE_INTERRUPTS();
    while(1);
}


#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	for(;;);
}
